services:
  calorieguide-db:
    image: postgres:16
    container_name: calorieguide-db
    environment:
      POSTGRES_USER: pgs
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgs
    ports:
      - '5432:5432'
    volumes:
      - ./_data:/var/lib/postgresql/data:z
      - ./sql_scripts:/docker-entrypoint-initdb.d

  calorie_guide:
    container_name: calorie_guide
    build: app/
    ports: 
      - "80:8090"
    environment:
      jwt_key: ${jwt_key}
      address: ${address}
      password: ${password}
      username: ${username}
      db: ${db}
    depends_on:
      - calorieguide-db
